plugins:
  ubiquity-os-marketplace/command-start-stop@demo:
  ubiquity-os/command-demo@demo:
  ubiquity-os-marketplace/command-wallet@demo:
  ubiquity-os-marketplace/command-query@demo:
  ubiquity-os-marketplace/text-conversation-rewards@demo:
    with:
      incentives:
        collaboratorOnlyPaymentInvocation: false
        contentEvaluator: {}
        userExtractor: {}
        dataPurge: {}
        formattingEvaluator: {}
        payment: {}
        githubComment: {}
        reviewIncentivizer: {}
        simplificationIncentivizer: {}
        externalContent: {}
  ubiquity-os-marketplace/daemon-disqualifier@demo:
  ubiquity-os-marketplace/text-vector-embeddings@demo:
    with:
      demoFlag: true
